services:
  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: martin

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stoppednpm
    ports:
      - 9444:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_ARBITRARY=1

volumes:
  postgres-data:
  mysql-data:
